### PR TITLE
Added proper margin for feedback page

### PR DESCRIPTION
**Pull request by psankhe28**
#71

### CODE REVIEW

**Comment by biratdatta** [comment]
Hey, @psankhe28 Can you fix the merge conflicts and describe what you have solved? 

Happy to help you out if you have further questions.

**Comment by psankhe28** [comment]
image

I have added a proper margin to the button.

**Comment by biratdatta** [comment]
image
Your PR has some merge conflicts. Can you fix that?

**Comment by prtkjakhar** [comment]
Fixed by another PR

**Pull request closed without merging**
