### PR TITLE
enhancement(#75) corrected the extra white space issue in the bottom of the navigation menu 

### LINKED ISSUE #75: Enhancement : Unwanted white space in the bottom of the navigation menu
image

In case of mobile navigation menu is scrollable with extra white space at botton.

- [x] correct the extra white space issue

### PR DESCRIPTION
**Pull request by ma1hotraz**
closes #75 

Added dynamic background coloring to the Sidebar component, aligning the background of `.css-4t3x6l-MuiPaper-root-MuiDrawer-paper` with the theme's primary dark color for improved consistency.

**Testing:**
Thoroughly tested across various resolutions and devices.

### CODE REVIEW

**Comment by biratdatta** [comment]
Hey @ma1hotraz , in your latest [PR](https://ui-templates-git-fork-ma1hotraz-fix-75-samagra-uci.vercel.app/) , there is an issue with the navbar having white space
image

Check it out once, and I am happy to answer other  questions that you have

**Comment by ma1hotraz** [comment]
@biratdatta I have fixed the issue in the latest commit. Please check. Thanks

**Comment by ma1hotraz** [comment]
@biratdatta  Find it here [PR](https://ui-templates-git-fork-ma1hotraz-fix-75-samagra-uci.vercel.app/)

**Comment by prtkjakhar** [comment]
@ma1hotraz can you take the latest pull of dev branch and push a commit?

**Comment by ma1hotraz** [comment]
@prtkjakhar  I have taken pull from the dev branch. Please check now.

**Comment by prtkjakhar** [comment]
@ma1hotraz vercel build is failing, can you build on local and resolve those issues?

**Comment by ma1hotraz** [comment]
> @ma1hotraz vercel build is failing, can you build on local and resolve those issues?

unable to see the issues.

**Comment by ma1hotraz** [comment]
> @ma1hotraz vercel build is failing, can you build on local and resolve those issues?

need to login into vercel to see those issues, dont have access

**Comment by prtkjakhar** [comment]
> > @ma1hotraz vercel build is failing, can you build on local and resolve those issues?
> 
> need to login into vercel to see those issues, dont have access

You can see those errors if you build it on local also.

**Comment by ma1hotraz** [comment]
> > > @ma1hotraz vercel build is failing, can you build on local and resolve those issues?
> > 
> > 
> > need to login into vercel to see those issues, dont have access
> 
> You can see those errors if you build it on local also.

The recently merged PR `chat_ui` is having problems. looking into it

**Comment by prtkjakhar** [comment]
> > > > @ma1hotraz vercel build is failing, can you build on local and resolve those issues?
> > > 
> > > 
> > > need to login into vercel to see those issues, dont have access
> > 
> > 
> > You can see those errors if you build it on local also.
> 
> The recently merged PR `chat_ui` is having problems. looking into it

try with the latest pull of dev branch now

**Comment by ma1hotraz** [comment]
@prtkjakhar done!
That build issue was caused do to overriding if the types. I asked kavikumar to fix it. Now he has fixed it

**Comment by prtkjakhar** [comment]
> @prtkjakhar done! That build issue was caused do to overriding if the types. I asked kavikumar to fix it. Now he has fixed it

This issue seems to be already fixed on the main link, closing the issue as solved.

**Comment by ma1hotraz** [comment]
Is the white space issue solved?

**Comment by ma1hotraz** [comment]
@prtkjakhar its still there, the issue isnt resolved, please reopen it so that i can fix it.

image

**Comment by prtkjakhar** [comment]
> @prtkjakhar its still there, the issue isnt resolved, please reopen it so that i can fix it.
> 
> image

vercel deployment has failed for your PR can you fix your build, have reopened the issue

**Comment by ma1hotraz** [comment]
@prtkjakhar fixed [PR](https://ui-templates-380jlwh0n-samagra-uci.vercel.app/)

**Pull request merged**
